### ISSUE TITLE
ValueError ValueError: could not convert string to float: 'www.facebook.com'

### ISSUE THREAD

**Issue by Prernapachpande** [chamanthmvs/Phishing-Website-Detection#2]
I'm getting thiserror when I check the url "ValueError
ValueError: could not convert string to float: 'www.facebook.com'"

**Comment by tushlal** [comment]
Even i got same error

**Comment by tushlal** [comment]
and also this error:
TypeError                                 Traceback (most recent call last)
<ipython-input-46-985bf3b5a627> in <module>
----> 1 splitted_data['abnormal_url'] = splitted_data['domain_name'].apply(abnormal_url_main)

~\anaconda3\lib\site-packages\pandas\core\series.py in apply(self, func, convert_dtype, args, **kwds)
   3846             else:
   3847                 values = self.astype(object).values
-> 3848                 mapped = lib.map_infer(values, f, convert=convert_dtype)
   3849 
   3850         if len(mapped) and isinstance(mapped[0], Series):

pandas\_libs\lib.pyx in pandas._libs.lib.map_infer()

TypeError: abnormal_url_main() missing 1 required positional argument: 'url'

**Comment by jetlingkarthik** [comment]
I got the same **ValueError**.

**Comment by jetlingkarthik** [comment]
How to resolve the ValueError issue?

**Comment by chamanthmvs** [comment]
Yes, because you are passing a string (this string should be processed and converted into numerical form) as we know that, machine learning algorithms can only process numerical data. 

So, include same preprocessing steps, which were included in training phase and then submit the required url to obtain the result.

Please try to understand the code and run it.
